# Python CircleCI 2.0 configuration file
version: 2.1
orbs:
    snyk: snyk/snyk@0.0.8
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: prod
      DH_IMAGE_NAME: microblog_prod


    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  snyk:
    docker:
        - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                make install
        - run: echo "source ~/repo/venv/bin/activate" >> $BASH_ENV # här gör vi så att så att CircleCi automatisk laddar venv och då kollar Snyk vad vi har installerat i den.
        - snyk/scan
  test:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests with docker
          command: |
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            make test
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image production
          command: docker-compose up --build -d $IMAGE_NAME
      - run:
          name: Tag build with latest
          command: docker tag $DH_IMAGE_NAME:latest wissamsawah/microblog-prod:latest
      - run:
          name: Archive Docker image
          command: docker save -o image.tar wissamsawah/microblog-prod
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin
            docker push wissamsawah/microblog-prod:latest

  ansible:
    executor: docker-publisher
    steps:
        - checkout
        - run:
            name: Install ansible
            command: |
                sudo apt-get install python3-venv
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements/deploy.txt
                pip install ansible
                pip install ansible[azure]
        - run:
            name: Run ansible playbook
            command: |
                . ../venv/bin/activate
                pip install ansible[azure]
                ansible-playbook gather_vm_instances.yml app_server.yml
            working_directory: ansible

workflows:
      version: 2
      build-master:
        jobs:
          - snyk:
            filters:
              branches:
                only: master
          - test:
            filters:
              branches:
                only: master
          - build:
              requires:
                - test
              filters:
                branches:
                  only: master
          - publish-latest:
              requires:
                - build
              filters:
                branches:
                  only: master
          - ansible:
              requires:
                - publish-latest
              filters:
                branches:
                  only: master
