version: "3"

services:
  test:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_test

    image: microblog_test:latest

    container_name: microblog_test
    volumes:
      - ./app:/home/microblog_test/app
      - ./tests:/home/microblog_test/tests
    restart:
            "always"

  prod:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_prod
    image: microblog_prod:latest
    container_name: microblog-production
    links:
          - "db:microblog-database"
    ports:
      - "8000:5000"
    environment:
          - SECRET_KEY=production
          - DATABASE_URL=mysql+pymysql://microblog:Wesam1995@{{ groups['database'][0] }}/microblog

    restart:
            "always"
    networks:
      microblog-network:

  db:
    image: mysql/mysql-server:5.7
    container_name: "microblog-database"
    environment:
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=Wesam1995
    volumes:
      - ./mysql-data:/var/lib/mysql

    restart:
            "always"

    networks:
      microblog-network:

prod_no_db:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_prod
    image: microblog_prod:latest
    container_name: prod_no_db
    links:
          - "db:microblog-database"
    ports:
      - "8000:5000"
    environment:
          - SECRET_KEY=production2
          - DATABASE_URL=mysql+pymysql://microblog:Wesam1995@{{ groups['database'][0] }}/microblog

    restart:
            "always"
    networks:
      microblog-network:

start:
    container_name: start
    image: wissamsawah/microblog_prod:latest
    restart: always
    ports:
      - "8000:5000"

    networks:
      microblog-network:

networks:
  microblog-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/16"
