FROM python:3.6-alpine

RUN adduser -D microblog

WORKDIR /home/microblog

COPY requirements.txt requirements.txt
COPY requirements requirements
COPY Makefile Makefile
COPY pytest.ini pytest.ini
COPY tests tests
COPY app app
COPY migrations migrations



RUN python3 -m venv venv
RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev make python3-dev py-pip build-base \
    && venv/bin/pip install --upgrade pip \
    && venv/bin/pip install -r requirements/test.txt
RUN venv/bin/pip install gunicorn
RUN venv/bin/pip install gunicorn pymysql

COPY test.sh .
COPY .bandit.yml .
RUN chmod +x test.sh
RUN chmod +x .bandit.yml

ENTRYPOINT ["./test.sh"]
