---

-   name: Remove exesting microblog container
    docker_container:
        name: "{{ docker_container_name }}"
        state: absent

- name: "Launch docker container with microblog application"
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    network_mode: host
    # ports:
    #   - "{{ host_port }}:{{ container_port }}"
    restart: True
    env:
      DATABASE_URL: "mysql+pymysql://microblog:Wesam1995@{{ groups['database'][0] }}/microblog"

- name: Remove statsd-exporter container
  docker_container:
    name: statsd-exporter
    state: absent

-   name: Pull the statsd container
    command: docker pull prom/statsd-exporter

-   name: Template the statsd conf file
    template:
        src: ./templates/statsd.conf.j2
        dest: statsd.conf
        owner: deploy
        group: deploy
        mode: ugo+rwx

-   name: Start the statsd container
    command: docker run -dP --net=host -v ${PWD}/statsd.conf:/statsd/statsd.conf prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"
