---
- name: "Launch docker container with microblog application"
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    ports:
      - "{{ host_port }}:{{ container_port }}"
    restart_policy: always
    env:
      DATABASE_URL: "mysql+pymysql://microblog:Wesam1995@{{ groups['database'][0] }}/microblog"

-   name: Pull the statsd container
    command: docker pull prom/statsd-exporter

-   name: Template the statsd conf file
    template:
        src: ./templates/statsd.conf.j2
        dest: statsd.conf
        owner: deploy
        group: deploy
        mode: ugo+rwx

-   name: Start the statsd container
    command: docker run -dP --net=host -v ${PWD}/statsd.conf:/statsd/statsd.conf prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"
