
packages:
  - "apt-transport-https"
  - "ca-certificates"
  - "cron"
  - "gnupg2"
  - "software-properties-common"

pip_packages:
  - "python-setuptools"

pip_packages:
  - "python-setuptools"

docker_channel: ["stable"]
docker_repo: >
  deb [arch=amd64]
  https://download.docker.com/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} {{ docker_channel | join (' ') }}
