---
- name: Install docker and packages
  apt:
    name: "{{ packages + pip_packages }}"

- name: Add Docker apt key
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: Configure docker apt repo
  apt_repository:
    repo: "{{ docker_repo }}"
    update_cache: true

- name: Install pip
  apt:
    name: python3-pip

- name: Install docker
  pip:
    name: "docker"
    executable: pip3

- name: Install docker-compose
  pip:
    name: "docker-compose"
    executable: pip3

- name: Install docker-ce
  apt:
    name: "docker-ce"
    state: "present"
